# Configuration file for ScheduledResource schedule widget.
# 

ResourceKinds:
# Resource:             Resource Use
  ZTimeHeaderDay:       ZTimeLabelDay
  ZTimeHeaderHour:      ZTimeLabelHour
  Station:              Event

visibleTime: 3.hours
       
Resources:
   - ZTimeHeaderDay       -8
   - ZTimeHeaderHour      -8
   - Station              60 2
   - Station              3 
   - Station              703 
   - Station              709
#   - Station              189 190 220
   - ZTimeHeaderHour      -8.
#   - Station              550 551
   - Station              37
#                            737 
   - Station              42
#                            738
   - Station              756
   - Station              757
   - Station              49 
   #                      798
   - Station              162
   #                    810
   #                    738
