# Configuration file for Timeline schedule widget.
# 

ResourceKinds:
# Resource:             Resource Use
  Station:              Event
  TimeheaderDayNight:   TimelabelDayNight
  TimeheaderHour:       TimelabelHour

visibleTime: 3.hours
       
Resources:
   - TimeheaderDayNight   dayNight0
   - TimeheaderHour       hour0
   - Station              3 
   - Station              703 
   - Station              709 60 189 190
   - TimeheaderHour       hour1
   - Station              37 737 
   - Station              42 738
   - Station              756
   - Station              757
   - Station              49 798 
   - Station              162 810
   #                    738
