# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4776c984ef5298ca573e3d255577254731bcba57145222cf362959bd78053d41272ec327cf9364eb54db87c8657966ed54587c564bca208c4a272baa562c99a4

test:
  secret_key_base: b2abd3922e1fafad8ddae0a89f3e32bf46f098207bfffa1b0d240d73c2cfc7f84911523ad6cdc19077a08fe3f3272dacaaa9dc711cef12e6227c0735f4047f42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
